# Generated by Django 4.2.2 on 2023-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='aryan', max_length=100),
            preserve_default=False,
        ),
    ]
